server:
  port: 8080

spring:
  jackson:
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1s0c914vjsarikavo.mysql.rds.aliyuncs.com:3306/museumappointmentsystem?useUnicode=true & characterEncoding=utf-8 &
      useSSL=true & serverTimezone=GMT%2B8 & allowPublicKeyRetrieval=true

    username: ycs
    password: 740909Yy

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.AppointmentSystem.Entity

